Semantic Satiation among Lexically Ambiguous Words: Experiment 2
================================================================

Acquiring the Data
------------------

We will first download the raw CSV from github and do a bit of preprocessing on it:

```{r, echo=FALSE, results='hide'}
library(nlme)
library(multcomp)
```

```{r}
download.file("https://github.com/faulconbridge/semsat/raw/master/Semsat2/semsat2.csv", "semsat2.csv", "wget", extra="--no-check-certificate")
semsat2 <- read.csv("semsat2.csv",header=TRUE,sep=",")

raw <- semsat2

# Strip out all filler and incorrectly-answered items
raw <- subset(raw, (BIAS=="dominant" & ANSWER=="M") |
                (BIAS=="subordinate" & ANSWER=="M") |
                (BIAS=="unrelated" & (HomType=="NV" | HomType=="NN")
                 & ANSWER=="C"),
              select=c(PID,BIAS,HomType,REPS,
                       ANSWER,MS,MS.3.STDEV,MS.IQR))

# Specify which variables should be treated as factors
raw <- within(raw, {
  BIAS <- factor(BIAS)
  HomType <- factor(HomType)
  REPS <- factor(REPS)
  PID <- factor(PID)
  STDEV <- MS.3.STDEV
  IQR <- MS.IQR
})

# Strip out participants who encountered bugs during the experiment
raw <- subset(raw, PID!=57 & PID!=42 & PID!=14,
              select=c(PID,BIAS,HomType,REPS,
                       ANSWER,MS,STDEV,IQR))

# Subset data to include untrimmed MS response times
raw.MS <- subset(raw,select=c(PID:MS))
raw.MS <- na.omit(raw.MS)

# Take the participant average RTs for each condition
raw.mean.MS <- aggregate(raw.MS$MS,
                      by=list(raw.MS$PID,raw.MS$BIAS,
                              raw.MS$HomType,raw.MS$REPS),
                      FUN='mean')
colnames(raw.mean.MS) <- c("PID","BIAS","HomType","REPS","MS")

# Subset the data to remove outliers beyond +-3 sd
raw.stdev <- subset(raw, select=c(PID,BIAS,HomType,REPS,STDEV))
raw.stdev <- na.omit(raw.stdev)

# Take the participant average RTs for each condition

raw.mean.stdev <- aggregate(raw.stdev$STDEV,
                      by=list(raw.stdev$PID,raw.stdev$BIAS,
                              raw.stdev$HomType,raw.stdev$REPS),
                      FUN='mean')
colnames(raw.mean.stdev) <- c("PID","BIAS","HomType","REPS","STDEV")
```

Performing the Analyses
-----------------------
First we can look at the untrimmed data:
```{r,echo=1}
raw.aov <- aov(MS ~ BIAS*HomType*REPS+Error(PID/(BIAS*HomType*REPS)),
               data=raw.mean.MS)
summary(raw.aov)
```

Then trimming based on standard deviations:
```{r,echo=1}
stdev.aov <- aov(STDEV ~ BIAS*HomType*REPS+Error(PID/(BIAS*HomType*REPS)),
                     data=raw.mean.stdev)
summary(stdev.aov)
```

Now we can run two 3x2 ANOVAs on the NN/NV data separately:
```{r}
NN <- subset(raw.mean.stdev, HomType=="NN", select=c(PID:STDEV))
nn.aov <- aov(STDEV ~ BIAS*REPS+Error(PID/(BIAS*REPS)),
                     data=NN)
summary(nn.aov)

NV <- subset(raw.mean.stdev, HomType=="NV", select=c(PID:STDEV))
nv.aov <- aov(STDEV ~ BIAS*REPS+Error(PID/(BIAS*REPS)),
                     data=NV)
summary(nv.aov)
```

And some t-tests to look at the ambiguity effect:
```{r}
dom <- subset(raw.mean.stdev, BIAS=="dominant", select=c(STDEV))
sub <- subset(raw.mean.stdev, BIAS=="subordinate", select=c(STDEV))
unrel <- subset(raw.mean.stdev, BIAS=="unrelated", select=c(STDEV))

NVsub3 <- subset(raw.mean.stdev, BIAS=="subordinate" & HomType=="NV" & REPS=="short",select=c(STDEV))
NVsub30 <- subset(raw.mean.stdev, BIAS=="subordinate" & HomType=="NV" & REPS=="long",select=c(STDEV))
NVunrel3 <- subset(raw.mean.stdev, BIAS=="unrelated" & HomType=="NV" & REPS=="short",select=c(STDEV))
NVunrel30 <- subset(raw.mean.stdev, BIAS=="unrelated" & HomType=="NV" & REPS=="long",select=c(STDEV))

t.test(dom$STDEV,sub$STDEV)
t.test(NVsub3$STDEV,NVunrel3$STDEV)
t.test(NVsub30,NVunrel30)
```